update readme
a11yphant/a11yphant pull request #7
Opened 2023-02-27 09:50 UTC by hntrhfr

i updated the github API token guide

2023-03-05 09:19 UTC, lucapircher commented on Readme.md
> +  - `npm login --scope=@OWNER --auth-type=legacy --registry=https://npm.pkg.github.com` with your github user and the token as password
```suggestion
  - `npm login --scope=@a11yphant --auth-type=legacy --registry=https://npm.pkg.github.com` with your github user and the token as password
```

We could insert the correct scope in the command here. I can already see myself trying to login for the `@OWNER` scope...

2023-03-05 09:20 UTC, lucapircher requested changes
Please also update the title in the readme file. We should have done that a long time ago

2023-03-06 09:59 UTC, hntrhfr commented
> Please also update the title in the readme file. We should have done that a long time ago

done

2023-03-06 10:03 UTC, hntrhfr reviewed
nice

2023-03-06 10:03 UTC, lucapircher approved these changes

2023-03-10 06:18 UTC, thomasdax98 commented on Readme.md
> -![coverage](https://gitlab.mediacube.at/a11yphant/a11yphant/badges/develop/coverage.svg)
Wieso hast du die Coverage ganz entfernt? Geht das auf Github nicht?

2023-03-10 07:23 UTC, lucapircher commented on Readme.md
> -![coverage](https://gitlab.mediacube.at/a11yphant/a11yphant/badges/develop/coverage.svg)
Github has no integrated support for code coverage. We will have to setup an external tool like codecov or codeclimate to bring such functionality back.

2023-03-10 08:34 UTC, merged